//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class InformacjeOKlientach
{
    public int ID { get; set; }
    public string GUID { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string Address { get; set; }
    public int PostalCode { get; set; }
}

public partial class Koszyk
{
    public int ID { get; set; }
    public string KlientID { get; set; }
    public int ProduktID { get; set; }
    public int Ilosc { get; set; }
    public Nullable<System.DateTime> DataZakupu { get; set; }
    public bool JestwKoszyku { get; set; }

    public virtual Produkty Produkty { get; set; }
}

public partial class Opinie
{
    public int Id { get; set; }
    public string Imie { get; set; }
    public string Email { get; set; }
    public string Opinia { get; set; }
}

public partial class Produkty
{
    public Produkty()
    {
        this.Koszyks = new HashSet<Koszyk>();
        this.Wysylkas = new HashSet<Wysylka>();
    }

    public int Id { get; set; }
    public int TypeId { get; set; }
    public string Nazwa { get; set; }
    public Nullable<double> Cena { get; set; }
    public string Opis { get; set; }
    public string Zdjecie { get; set; }

    public virtual ICollection<Koszyk> Koszyks { get; set; }
    public virtual TypyProduktow TypyProduktow { get; set; }
    public virtual ICollection<Wysylka> Wysylkas { get; set; }
}

public partial class TypyProduktow
{
    public TypyProduktow()
    {
        this.Produkties = new HashSet<Produkty>();
    }

    public int Id { get; set; }
    public string Name { get; set; }

    public virtual ICollection<Produkty> Produkties { get; set; }
}

public partial class Wysylka
{
    public int Id { get; set; }
    public string KlientId { get; set; }
    public Nullable<int> IdProdukt { get; set; }
    public string Wiadomosc { get; set; }
    public string JakPlaci { get; set; }
    public string JakWyslac { get; set; }

    public virtual Produkty Produkty { get; set; }
}
